@startuml
left to right direction
actor "Patient" as patient
rectangle "Mister ED Healthcare System" {
  rectangle "Account Management" {
    usecase "Register Account" as UC1
    usecase "Log In / Out" as UC2
  }
  rectangle "Health Profile" {
    usecase "Update Health Profile" as UC3
    usecase "View Medical History" as UC11
  }
  rectangle "Hospital Services" {
    usecase "Find Nearby Hospitals" as UC4
    usecase "View Hospital Wait Times" as UC5
    usecase "View Waitlist Position" as UC9
    usecase "Leave Waitlist" as UC10
  }
  usecase "Call Emergency Hotline" as UC6
  rectangle "Virtual Triage" {
    usecase "Register for Virtual Triage" as UC7
    usecase "View Triage Results" as UC8
  }
}

patient --> UC1
patient --> UC2
patient --> UC4
patient --> UC6
patient --> UC7
patient --> UC9

UC1 ..> UC3 : includes
UC2 ..> UC11 : includes
UC2 ..> UC3 : includes
UC7 ..> UC8 : includes
UC4 <|-- UC5 : extends
UC9 <|-- UC10 : extends

@enduml